[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
runOnSave = true
port = 8501
address = "0.0.0.0"

[ui]
hideTopBar = false
hideSidebarNav = false